spring:
  application:
    name: eureka
server:
  port: 18000
eureka:
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:18000/eureka/
