spring:
  application:
    name: consumer-plus
  main:
    allow-bean-definition-overriding: true
server:
  port: 19001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:18000/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 20
      queueSizeRejectionThreshold: 2
  command:
    provider:
      circuitBreaker:
        enabled: true
        forceOpen: true
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD